### PR TITLE
frenchdict and spanishdict

### PR DESCRIPTION
**Pull request by YoyPa**

### CODE REVIEW

**Comment by fourminute** [comment]
Amazing. I will give this a review and merge soon. Thank you @YoyPa !

**Comment by fourminute** [comment]
This is scheduled to be merged along with the other localisations and due for next release.

**Comment by fourminute** [comment]
Hello @YoyPa , can you please resolve these conflicts so I can merge this or submit a new pull with a single commit for easiest compatibility.

**Comment by YoyPa** [comment]
I will make a new pull in 10min

**Pull request closed without merging**
