### PR TITLE
Quality of Life improvements

### PR DESCRIPTION
**Pull request by TheZoc**
Hello,

I just created these utilities to aid in development, setup and running of Fluffy.

1. Added `requirements.txt` file
This allows for easy installation, by running `pip install -r requirements.txt`

2. Added `run.bat` and `setup.bat` utilites
These utilities substantially improve support for Fluffy on Windows.
    1. Uses a virtual environment, so the system install won't conflict with Fluffy's own virtual environment
    2. User-friendly. Only needs Python 3 installed!
    3. By having a local environment, it's easy to find issues and/or reinstall broken packages (just delete `venv`)

3. Added .gitignore
While minor, I thought this was a good addition to aid when adding and committing files. This will prevent unwanted stuff from being committed.

Give it a try and see how it works. It is fully compatible with 32 and 64 bits version of Python, but requires Python 3 to work correctly.

I hope you like it! :)

### CODE REVIEW

**Comment by fourminute** [comment]
I've decided against a Requirements manifest as the dependency list is already really small and fairly straight-forward. 

Does your method solve the dependency issue involving libusb most end-users experience? What is the benefit of a virtual environment over a portable executable?

**Comment by TheZoc** [comment]
> I've decided against a Requirements manifest as the dependency list is already really small and fairly straight-forward.

I thought `requirements.txt` would be a nice addition since it's hassle-free, standardized way of installing python packages. No need to search int he documentation for what packages are needed.

> Does your method solve the dependency issue involving libusb most end-users experience? What is the benefit of a virtual environment over a portable executable?

Yes, it will _significantly_ improve the success rate!
Virtual Environment is a way to keep all the libraries needed for a project running in their own "virtual environment". You (almost) completely sever its link with the system files and libraries, running a self-contained installation.

Give them a try on your side ([clone my fork](https://github.com/TheZoc/Fluffy)), and see how it works. It will create a `venv/` folder with all the required files inside (you can even uninstall packages from your system install, and you will see it works on the virtual environment).

Of course, there are many ways of getting a virtual environment to run, I just provided a simple one for windows users. I can help with linux/macOS ones if you like the idea 😉

**Comment by fourminute** [comment]
That's actually pretty neat. I will give this a try and report back.

**Comment by TheZoc** [comment]
I rebased my fork to keep it up to date with the master. I hope it helps :)

**Comment by Gee19** [comment]
These are really good changes, might be a good idea to make the setup.bat a little less brittle for people using python3/pip3. Also the gitignore is a bit excessive but that isn’t a big deal :) Great job

**Comment by TheZoc** [comment]
Thanks for the feedback @Gee19 !

I (only) use Python 3 on Windows environments.
From what I recall, the `python -m venv` only exists in Python 3 ( `virtualenv` is not supported due to issues with `pythonw.exe`, only stdlib `venv` is - I've tested 😉 ), and inside the virtual environment, pip and pip3 will be the same.

`.gitignore` is the recommended GitHub one, with the addition of `fluffy_config.py`. These files shouldn't be commited and `fluffy_config.py` sneaked in while I was doing my tests (everything was squashed together for this PR).

I think I managed to get everything super easy for Windows users. I'm still waiting on @fourminute feedback, but if there are changes you recommend or any mistakes you noticed, please, tell me!
I've tested this code quite a bit, everything should be working as intended 😀

**Comment by fourminute** [comment]
I'll be honest I've been  having some tough times back here at home haven't been able to put much work into Fluffy like I would have liked. Due to the Paradise fire I am somewhat homeless.

 I am sorry this took me so long to review, I am going to push this through. Thank you for this contribution.

**Pull request merged**
